apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-service
  title: Test Service
  description: Test service for updating entities page
  annotations:
    circleci.com/project-slug: butbucket/ninjarmm/kaizen
    jira.com/project-key: DPE
    pagerduty.com/service-id: PA36JR1
    "backstage.io/kubernetes-label-selector": "app=checkout-service"
spec:
  type: service
  lifecycle: production
  owner: group:default/pe-dpe
